PLUGIN_NAME=		caddy
PLUGIN_VERSION=		0.1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		A powerful, enterprise-ready, open source web server
PLUGIN_MAINTAINER=	github.nstein@mailbox.org

.include "../../Mk/plugins.mk"
